#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$local = file_exists(__DIR__ . '/config/local.php') ? require(__DIR__ . '/config/local.php') : [];

exit((new yii\console\Application(
    \yii\helpers\ArrayHelper::merge(
        require(__DIR__ . '/config/base.php'),
        \yii\helpers\ArrayHelper::getValue($local, 'base', []),
        require(__DIR__ . '/config/console.php'),
        \yii\helpers\ArrayHelper::getValue($local, 'console', [])
    )
))->run());
